// Generated by tyohnn. Type-level completeness: every installed library exports every semantic name.
import type * as phosphor from "./libraries/phosphor";
import type { IconComponent, IconName } from "./names";

type Complete<Library extends Record<IconName, IconComponent>> = Library;

export type IconLibraries = {
    phosphor: Complete<typeof phosphor>;
};
